const fs = require('fs');
const p = require('path').join(__dirname, 'data', 'promises.json');
let data = JSON.parse(fs.readFileSync(p, 'utf8')); 
const newPromises = [
  {slug:'monthly-college-allowance',title:'Monthly College Allowance',titleMl:'പ്രതിമാസ കോളേജ് അലവൻസ്',description:'₹1,000 per month for all female college-going students to facilitate higher education.',manifestoQuote:'We will provide a monthly allowance of ₹1,000 to all female college students to encourage higher education.',sector:{id:'s1',name:'Women & Welfare',nameMl:'സ്ത്രീകളും ക്ഷേമവും',icon:'users',color:'#2563EB'},status:'pending',icon:'graduation-cap',sources:[],lastUpdated:'2026-05-18T10:00:00Z',createdAt:'2026-05-18T10:00:00Z'},
  {slug:'youth-entrepreneurship-loans',title:'Youth Entrepreneurship Loans',titleMl:'യുവ സംരംഭക വായ്പകൾ',description:'Interest-free business startup loans of up to ₹5 lakh for young individuals.',manifestoQuote:'To foster a culture of entrepreneurship, we will provide interest-free startup loans up to ₹5 lakh for our youth.',sector:{id:'s6',name:'Employment',nameMl:'തൊഴിൽ',icon:'briefcase',color:'#9333EA'},status:'pending',icon:'banknote',sources:[],lastUpdated:'2026-05-18T10:00:00Z',createdAt:'2026-05-18T10:00:00Z'},
  {slug:'aviation-freight-push',title:'Aviation & Freight Push',titleMl:'ഏവിയേഷൻ & ഫ്രൈറ്റ് പുഷ്',description:'Major cargo and logistics upgrades across the state\'s four international airports.',manifestoQuote:'We will upgrade cargo and logistics infrastructure across all four international airports to boost trade.',sector:{id:'s4',name:'Infrastructure',nameMl:'അടിസ്ഥാന സൗകര്യങ്ങൾ',icon:'building',color:'#64748B'},status:'pending',icon:'plane',sources:[],lastUpdated:'2026-05-18T10:00:00Z',createdAt:'2026-05-18T10:00:00Z'},
  {slug:'wayanad-tribal-university',title:'Wayanad Tribal University',titleMl:'വയനാട് ട്രൈബൽ യൂണിവേഴ്സിറ്റി',description:'Establishing a dedicated central-model university for indigenous and tribal studies in Wayanad.',manifestoQuote:'A dedicated university for tribal studies will be established in Wayanad to preserve indigenous culture and provide higher education.',sector:{id:'s7',name:'Education',nameMl:'വിദ്യാഭ്യാസം',icon:'book-open',color:'#0284C7'},status:'pending',icon:'school',sources:[],lastUpdated:'2026-05-18T10:00:00Z',createdAt:'2026-05-18T10:00:00Z'},
  {slug:'foreign-university-collaborations',title:'Foreign University Collaborations',titleMl:'വിദേശ സർവകലാശാല സഹകരണം',description:'Partnering with premium international universities to build international standard campuses inside Kerala.',manifestoQuote:'We will partner with top-tier international universities to bring global educational standards to Kerala.',sector:{id:'s7',name:'Education',nameMl:'വിദ്യാഭ്യാസം',icon:'book-open',color:'#0284C7'},status:'pending',icon:'globe',sources:[],lastUpdated:'2026-05-18T10:00:00Z',createdAt:'2026-05-18T10:00:00Z'},
  {slug:'5-lakh-youth-jobs',title:'5 Lakh Youth Jobs',titleMl:'5 ലക്ഷം യുവജനങ്ങൾക്ക് തൊഴിൽ',description:'Implementing specialized skill development programs to provide employment to 500,000 youth over 5 years.',manifestoQuote:'Through targeted skill development, we will create 500,000 secure jobs for our youth over the next five years.',sector:{id:'s6',name:'Employment',nameMl:'തൊഴിൽ',icon:'briefcase',color:'#9333EA'},status:'pending',icon:'users',sources:[],lastUpdated:'2026-05-18T10:00:00Z',createdAt:'2026-05-18T10:00:00Z'},
  {slug:'msme-support',title:'MSME Support',titleMl:'എംഎസ്എംഇ പിന്തുണ',description:'Expanding credit availability and financial safety nets for MSMEs with a turnover of up to ₹100 crore.',manifestoQuote:'We will dramatically expand credit availability and safety nets for all MSMEs up to ₹100 crore turnover.',sector:{id:'s8',name:'Industry',nameMl:'വ്യവസായം',icon:'factory',color:'#475569'},status:'pending',icon:'store',sources:[],lastUpdated:'2026-05-18T10:00:00Z',createdAt:'2026-05-18T10:00:00Z'},
  {slug:'age-relaxation-kpsc',title:'KPSC Age Relaxation',titleMl:'കെപിഎസ്‌സി പ്രായപരിധി ഇളവ്',description:'Easing age caps for government job eligibility under KPSC to make up for backlogs.',manifestoQuote:'We will provide necessary age relaxations for KPSC exams to ensure candidates affected by delays get a fair chance.',sector:{id:'s6',name:'Employment',nameMl:'തൊഴിൽ',icon:'briefcase',color:'#9333EA'},status:'pending',icon:'clock',sources:[],lastUpdated:'2026-05-18T10:00:00Z',createdAt:'2026-05-18T10:00:00Z'},
  {slug:'5-lakh-homes',title:'5 Lakh Homes for the Homeless',titleMl:'ഭവനരഹിതർക്ക് 5 ലക്ഷം വീടുകൾ',description:'Overhauling the housing framework to guarantee 500,000 houses for homeless families.',manifestoQuote:'No family will be left without a roof. We will overhaul the housing scheme to build 500,000 homes.',sector:{id:'s3',name:'Social Security',nameMl:'സാമൂഹ്യ സുരക്ഷ',icon:'shield-check',color:'#1D4ED8'},status:'pending',icon:'home',sources:[],lastUpdated:'2026-05-18T10:00:00Z',createdAt:'2026-05-18T10:00:00Z'},
  {slug:'fuel-kerosene-subsidies',title:'Fuel & Kerosene Subsidies',titleMl:'ഇന്ധന, മണ്ണെണ്ണ സബ്സിഡികൾ',description:'Distributing subsidized fuel for fishing boats, KSRTC buses, auto-rickshaws, and taxi operators.',manifestoQuote:'To combat inflation, we will provide subsidized fuel and kerosene to fishing boats and public transport operators.',sector:{id:'s3',name:'Social Security',nameMl:'സാമൂഹ്യ സുരക്ഷ',icon:'shield-check',color:'#1D4ED8'},status:'pending',icon:'fuel',sources:[],lastUpdated:'2026-05-18T10:00:00Z',createdAt:'2026-05-18T10:00:00Z'},
  {slug:'no-bill-hospitals',title:'No-Bill Emergency Hospitals',titleMl:'നോ-ബിൽ അത്യാഹിത ആശുപത്രികൾ',description:'Creating zero-billing emergency treatment windows at public hospitals.',manifestoQuote:'Emergency healthcare should not lead to debt. We will establish zero-billing emergency windows in public hospitals.',sector:{id:'s2',name:'Health',nameMl:'ആരോഗ്യം',icon:'heart-pulse',color:'#15803D'},status:'pending',icon:'hospital',sources:[],lastUpdated:'2026-05-18T10:00:00Z',createdAt:'2026-05-18T10:00:00Z'},
  {slug:'panchayat-dialysis-units',title:'Panchayat Dialysis Units',titleMl:'പഞ്ചായത്ത് ഡയാലിസിസ് യൂണിറ്റുകൾ',description:'Fully funded dialysis centers operating across every single Grama Panchayat in Kerala.',manifestoQuote:'We will ensure every Grama Panchayat is equipped with a fully-funded public dialysis unit.',sector:{id:'s2',name:'Health',nameMl:'ആരോഗ്യം',icon:'heart-pulse',color:'#15803D'},status:'pending',icon:'activity',sources:[],lastUpdated:'2026-05-18T10:00:00Z',createdAt:'2026-05-18T10:00:00Z'},
  {slug:'affordable-wedding-auditoriums',title:'Affordable Wedding Auditoriums',titleMl:'മിതമായ നിരക്കിൽ വിവാഹ ഓഡിറ്റോറിയങ്ങൾ',description:'Building subsidized public marriage spaces to alleviate wedding expenses for lower-income groups.',manifestoQuote:'To reduce the financial burden of marriages, we will build affordable public wedding auditoriums across the state.',sector:{id:'s3',name:'Social Security',nameMl:'സാമൂഹ്യ സുരക്ഷ',icon:'shield-check',color:'#1D4ED8'},status:'pending',icon:'tent',sources:[],lastUpdated:'2026-05-18T10:00:00Z',createdAt:'2026-05-18T10:00:00Z'}
];
let maxId = Math.max(...data.map(d => parseInt(d.id.replace('p',''))));
newPromises.forEach(np => { maxId++; np.id = 'p' + maxId; data.push(np); });
fs.writeFileSync(p, JSON.stringify(data, null, 2));
